const permalinks = require('@metalsmith/permalinks')
const Metalsmith = require('metalsmith')

const redirectsPlugin = require('./index.js')

describe('Hash fingerprints plugin', () => {
  const source = './fixtures/src'
  const destination = './fixtures/build'

  let output
  let redirects

  beforeAll((done) => {
    Metalsmith(__dirname)
      // Use test fixtures
      .source(source)
      .destination(destination)

      // Redirects plugin requires permalinks to work
      .use(permalinks())

      // The redirects plugin under test
      .use(redirectsPlugin)

      // Build
      .build((err, files) => {
        if (err) {
          return done(err)
        }

        output = files

        // Split redirects file back out by line so we can match on entire lines
        // rather than e.g. expect(string).toContain()
        redirects = files._redirects.contents.toString().split('\n')

        done()
      })
  })

  it('creates a _redirects file', () => {
    expect(output).toHaveProperty('_redirects')
  })

  it('includes a generated by header', () => {
    expect(redirects).toEqual(
      expect.arrayContaining([expect.stringMatching(/^# Generated by/)])
    )
  })

  it('does not includes live pages in the _redirects file', () => {
    expect(redirects).not.toEqual(
      expect.arrayContaining([expect.stringContaining('/live')])
    )
  })

  it('includes archived pages in the _redirects file with a 410 status', () => {
    expect(redirects).toContain('/archived\t/archived\t410!')
  })

  it('includes redirects for pages that have moved', () => {
    expect(redirects).toContain('/old/page\t/redirected\t301')

    expect(redirects).toContain('/another/old-page\t/redirected\t301')
  })
})
