const outdent = require('outdent')

/**
 * Redirects plugin
 *
 * Creates a _redirects file in the build directory with redirects for:
 * - any 'archived' pages (defined as those which use layout-archived.njk)
 * - moved pages, with previous URLs defined as `redirects` in their frontmatter
 *
 * The redirects file is tab-separated, and looks like:
 *
 * /archived/page   /archived/page    410!
 * /moved/page    /new/page   301
 *
 * The ! on the 410 status code makes it a forced-redirect, which is needed
 * because Netlify will otherwise ignore redirects where the path exists.
 *
 * @see https://docs.netlify.com/manage/routing/redirects/overview/
 * @returns {import('metalsmith').Plugin} Metalsmith plugin
 */

module.exports = function redirects(files, metalsmith, done) {
  const archivedFiles = Object.values(files).filter(
    (file) => file?.layout === 'layout-archived.njk'
  )

  const archiveRedirects = archivedFiles
    .map((file) => `/${file.permalink}\t/${file.permalink}\t410!`)
    .join('\n')

  const movedFiles = Object.values(files)
    .filter((file) => file?.redirects)
    .flatMap((file) =>
      file.redirects.map((redirect) => [redirect, file.permalink])
    )

  const movedRedirects = movedFiles
    .map(([from, to]) => `/${from.replace(/^\/+/, '')}\t/${to}\t301`)
    .join('\n')

  files._redirects = {
    contents: Buffer.from(outdent`
      # Generated by lib/redirects/index.js
      # Archived pages
      ${archiveRedirects}

      # Moved pages
      ${movedRedirects}
      `),
    mode: '0664'
  }

  done()
}
