name: Check deleted pages

on: pull_request

jobs:
  check_deleted_pages:
    name: Check for deleted pages without an archive or redirect
    runs-on: 'ubuntu-22.04'
    permissions:
      pull_requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        with:
          fetch-depth: 0

      - name: Generate name-status diff
        run: git diff --name-status origin/${{ github.base_ref }} origin/${{ github.head_ref }} > diff.txt

      - name: Get deleted pages
        id: get-deleted-pages
        uses: actions/github-script@v9.0.0
        with:
          script: |
            const { getFilesFromDiff } = await import('${{ github.workspace }}/.github/workflows/scripts')
            return getFilesFromDiff()

      - name: Check if netlify.toml has netlify has changed
        if: steps.get-deleted-pages.outputs.result != 'false'
        id: netlify-changed
        uses: actions/github-script@v9.0.0
        with:
          script: |
            const { getNetlifyConfigChanged } = await import('${{ github.workspace }}/.github/workflows/scripts/diff-helpers.mjs')
            return getNetlifyConfigChanged()

      - name: Add comment if there are deleted pages
        if: steps.get-deleted-pages.outputs.result != 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "The following pages have been deleted in this pull request:" >> body.txt
          echo "" >> body.txt
          IFS=', ' read -r -a pages <<< "${{ steps.get-deleted-pages.outputs.result }}"
          for page in "${pages[@]}"
          do
            echo "- ${page}" >> body.txt
          done
          echo "" >> body.txt
          if [ "${{ steps.netlify-changed.outputs.result }}" == 'false' ]; then
            echo "There has also been no change detected to netlify.toml config file, meaning no redirects have been setup for any deleted pages." >> body.txt
            echo "" >> body.txt
          fi
          echo "If you have not already done so, please read our documentation on [handling deleted URLs](https://github.com/alphagov/govuk-design-system/blob/main/docs/contributing/handling-deleted-urls.md) and ensure the above deleted pages are handled properly." >> body.txt
          gh pr comment ${{ github.event.pull_request.number }} --body-file "body.txt" --edit-last --create-if-none

      - name: Explicitly fail if deleted pages and no netlify changes
        if: steps.get-deleted-pages.outputs.result != 'false' && steps.netlify-changed.outputs.result == 'false'
        run: exit 1
