name: Test

on:
  pull_request:

  push:
    branches:
      - 'feature/**'
      - 'v[0-9]'

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Build
        uses: ./.github/workflows/actions/install-and-build
        with:
          cache_install: 'true'

  test:
    name: ${{ matrix.task.description }}
    runs-on: 'ubuntu-24.04'
    needs: [build]

    strategy:
      fail-fast: false

      matrix:
        task:
          - description: Lint Sass
            run: npm run lint:scss

          - description: Lint JavaScript
            run: npm run lint:js

          - description: Lint HTML
            run: npm run lint:html --ignore-scripts

          - description: EditorConfig
            run: npm run lint:editorconfig

          - description: Prettier
            run: npm run lint:prettier

          - description: TypeScript compiler
            run: npm run lint:types -- --pretty

          # Puppeteer uses Chrome to execute tests.
          # Ubuntu requires an App Armor profile for developer builds of Chrome to run without errors.
          # (https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md)
          - description: JavaScript tests
            run: aa-exec --profile=chrome npx jest --color --maxWorkers=2

          - description: Check broken links
            run: npm run check-links

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.3

      - name: Restore build
        uses: ./.github/workflows/actions/install-and-build

      - name: Run task
        id: task
        run: ${{ matrix.task.run }}
        continue-on-error: ${{ matrix.task.continue-on-error || false }}

      - name: Task warnings
        if: steps.task.outcome == 'failure'
        run: echo "::warning title=${{ matrix.task.description }} task failed::Check has been temporarily ignored"
